"""add unique constraint

Revision ID: 6dcbe00b3e0f
Revises: 79060e64420f
Create Date: 2025-04-22 22:58:25.081360

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6dcbe00b3e0f"
down_revision: Union[str, None] = "79060e64420f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tagname",
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.Column("lang", sa.String(length=5), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["tag_id"], ["tag.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tag_id", "lang", "name", name="uq_tag_lang_name"),
    )
    op.create_index("ix_tag_name_lang_name", "tagname", ["lang", "name"], unique=False)
    op.create_unique_constraint("uq_company_lang_name_pair", "companyname", ["company_id", "lang", "name"])
    op.create_unique_constraint("uq_company_tag_pair", "companytag", ["company_id", "tag_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_company_tag_pair", "companytag", type_="unique")
    op.drop_constraint("uq_company_lang_name_pair", "companyname", type_="unique")
    op.drop_index("ix_tag_name_lang_name", table_name="tagname")
    op.drop_table("tagname")
    # ### end Alembic commands ###
