[pytest]
norecursedirs = .git migrations
python_files = test*
pythonpath = .
testpaths = tests
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
env =
    DATABASE_URL=mysql+pymysql://root:root@localhost:3306/wanted_test
